### ISSUE TITLE
Failed step "success" of plugin "@semantic-release/github"

### ISSUE THREAD

**Issue by seanxu007** [semantic-release/github#415] opened 2021-09-21 05:01 UTC
I ran `npx semantic-release` in my Github pipeline with my `GITHUB_TOKEN`.

Everything went well. A new tag is published, but there comes an error at the last step `Failed step "success" of plugin "@semantic-release/github"`.

Logs show below:

![image](https://user-images.githubusercontent.com/8446958/134113895-31115f85-6071-4922-9f1e-8f042440650e.png)

**Is there anyone who can help me~~ Thanks a lot~~**

**Comment by josh-barker** [comment] 2021-09-21 05:02
I have observed the same behaviour.

**Comment by josh-barker** [comment] 2021-09-21 05:43
I also found that if I used `curl` with my token, I'm able to get the issue details using the endpoint in the error.
That leads me to believe it could be a timing issue.

**Comment by skilbjo** [comment] 2021-09-21 05:47
I am getting a similar (although not exact) error in https://github.com/cycjimmy/semantic-release-action/issues/80

**Comment by krishna-acondy** [comment] 2021-09-21 07:43
We've also started having this exact same issue in https://github.com/sasjs/cli.

https://github.com/sasjs/cli/runs/3660512107

Any help on this would be great, thank you! 🙏🏽

**Comment by ravali-rimmalapudi** [comment] 2021-09-21 08:05
I am also getting the same error today https://github.com/semantic-release/git/issues/298

**Comment by RappC** [comment] 2021-09-21 10:56
See the same error, but only if branch protection is turned on for the release branch. If branch protection is not enabled it is working as expected.

**Comment by Spaideri** [comment] 2021-09-21 12:19
Posting to raise priority, we are facing the same issue

**Comment by Christos-Zacharopoulos** [comment] 2021-09-21 12:34
Seeing the same error!

**Comment by tthyt** [comment] 2021-09-21 13:41
I was able to work around this error by suppressing the success commenting in `.releaserc`

```
        [
            "@semantic-release/github",
            {
                "successComment": false
            }
        ],

```
That way the problematic issue search query is skipped and the GH release can be created least.

**Comment by tthyt** [comment] 2021-09-21 14:31
This seems to be related https://github.com/octokit/rest.js/issues/114

**Comment by aanthonyrizzo** [comment] 2021-09-21 14:32
I tried reverting to a previous release(semantic-release@17.4.7) and that did not seem to fix the issue either. I did not try earlier releases but it seems @tthyt has the only current workaround.

**Comment by seanxu007** [comment] 2021-09-21 22:20
Thank you @tthyt, to pass over it will be a great solution currently~

**Comment by travi** [comment] 2021-09-21 22:24
Are folks still seeing this failure? I did see this happen with one of my projects last night, but have seen several releases complete successfully today with the default config. If this was just an API problem that has been fixed, I would like to close this issue. If folks are still seeing this happen, we can keep it open until we understand better.

**Comment by gr2m** [comment] 2021-09-21 22:38
I was trying to reproduce the problem in octokit/rest.js#114 but to no avail either. I also did several releases myself with both semantic-release 17 & 18 today and have not seen the error.

**Comment by gr2m** [comment] 2021-09-21 23:11
Mystery solved, please update your lock files, make sure you don't have `node-fetch` v2.6.3 in there

**Closed by gr2m** 2021-09-21 23:11 UTC
